project_id = "spwgfdszzbmpzwraocra"

[functions.create-checkout]
verify_jwt = false

[functions.verify-payment]
verify_jwt = false

[functions.stripe-webhook]
verify_jwt = false

[functions.setup-admin]
verify_jwt = false

[functions.send-order-status-email]
verify_jwt = false

[functions.delete-account]
verify_jwt = false

[functions.get-users-auth-status]
verify_jwt = false

[functions.admin-user-actions]
verify_jwt = false

[functions.send-contact-email]
verify_jwt = false
